export const aiFunctions = [
	{
		name: 'Client Engagement & Accountability Bots',
		label: 'Accountability Bots',
		href: '/admin/client-engagement-accountability-bots',
		description: 'Automated, intelligent bots to provide check-ins, reminders, and encouragement to keep clients on track.',
		isInstalled: true,
	},
	{
		name: 'Personalized Goal Setting & Action Planning',
		label: 'Goal Setting',
		href: '/admin/personalized-goal-setting-action-planning',
		description: 'AI-driven tools to help clients define, refine, and create actionable steps towards their personal and professional goals.',
		isInstalled: true,
	},
	{
		name: 'Personalized Intake Tool',
		label: 'Intake Tool',
		href: '/admin/personalized-intake-tool',
		description: 'An AI-powered tool that personalizes the initial interaction with potential clients through a dynamic contact form.',
		isInstalled: true,
	},
	{
		name: 'Dynamic Progress Tracking & Visualization',
		label: 'Progress Tracking',
		href: '/admin/dynamic-progress-tracking-visualization',
		description: 'Visually track and analyze progress towards goals with AI-powered insights and dynamic charts.',
		isInstalled: false,
	},
	{
		name: 'Intelligent Habit Formation & Breaking',
		label: 'Habit Formation',
		href: '/admin/intelligent-habit-formation-breaking',
		description: 'Leverage AI to understand habit loops and receive personalized strategies for forming positive habits and breaking negative ones.',
		isInstalled: false,
	},
	{
		name: 'Emotional Intelligence & Resilience Development',
		label: 'Emotional Intelligence',
		href: '/admin/emotional-intelligence-resilience-development',
		description: 'AI-driven exercises and feedback to enhance emotional awareness, empathy, and resilience in challenging situations.',
		isInstalled: false,
	},
	{
		name: 'Decision-Making Support & Scenario Analysis',
		label: 'Decision Support',
		href: '/admin/decision-making-support-scenario-analysis',
		description: 'Utilize AI to analyze potential outcomes of difficult decisions and gain clarity on the best path forward.',
		isInstalled: false,
	},
	{
		name: 'Communication Skills Enhancement',
		label: 'Communication Skills',
		href: '/admin/communication-skills-enhancement',
		description: 'Receive AI-based feedback on communication patterns to improve clarity, confidence, and impact in conversations.',
		isInstalled: false,
	},
	{
		name: 'Personalized Stress & Well-being Management',
		label: 'Stress Management',
		href: '/admin/personalized-stress-well-being-management',
		description: 'AI-powered tools to identify stress triggers and recommend personalized mindfulness and well-being exercises.',
		isInstalled: false,
	},
	{
		name: 'Time Management & Productivity Optimization',
		label: 'Time Management',
		href: '/admin/time-management-productivity-optimization',
		description: 'Optimize schedules and workflows with AI-driven analysis of productivity patterns and time usage.',
		isInstalled: false,
	},
	{
		name: 'Resource Recommendation Engine',
		label: 'Resource Engine',
		href: '/admin/resource-recommendation-engine',
		description: 'An AI engine that suggests relevant articles, books, and other resources based on client needs and goals.',
		isInstalled: false,
	},
	{
		name: 'Mindset & Belief System Analysis',
		label: 'Mindset Analysis',
		href: '/admin/mindset-belief-system-analysis',
		description: 'AI tools to help identify and challenge limiting beliefs that may be holding clients back.',
		isInstalled: false,
	},
	{
		name: 'Conflict Resolution Coaching',
		label: 'Conflict Resolution',
		href: '/admin/conflict-resolution-coaching',
		description: 'Simulate and practice difficult conversations with an AI coach to build conflict resolution skills.',
		isInstalled: false,
	},
	{
		name: 'Career Pathing & Skill Development',
		label: 'Career Pathing',
		href: '/admin/career-pathing-skill-development',
		description: 'AI-driven guidance on career transitions, skill-gap analysis, and professional development planning.',
		isInstalled: false,
	},
	{
		name: 'Personal Finance Habits & Budgeting Guidance',
		label: 'Finance Habits',
		href: '/admin/personal-finance-habits-budgeting-guidance',
		description: 'AI-powered tools for building healthy financial habits, creating budgets, and planning for financial goals.',
		isInstalled: false,
	},
	{
		name: 'Work-Life Balance Optimization',
		label: 'Work-Life Balance',
		href: '/admin/work-life-balance-optimization',
		description: 'Analyze schedules and commitments with AI to find opportunities for better balance and reduced burnout.',
		isInstalled: false,
	},
];
