// Inspired by https://www.figma.com/community/file/1065604674393325609/shadcn-ui-color-theme-generator

const hexToHsl = (hex: string): string => {
  let r = 0, g = 0, b = 0;
  if (hex.length === 4) {
    r = parseInt(hex[1] + hex[1], 16);
    g = parseInt(hex[2] + hex[2], 16);
    b = parseInt(hex[3] + hex[3], 16);
  } else if (hex.length === 7) {
    r = parseInt(hex[1] + hex[2], 16);
    g = parseInt(hex[3] + hex[4], 16);
    b = parseInt(hex[5] + hex[6], 16);
  }
  r /= 255; g /= 255; b /= 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  let h = 0, s = 0, l = (max + min) / 2;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r: h = (g - b) / d + (g < b ? 6 : 0); break;
      case g: h = (b - r) / d + 2; break;
      case b: h = (r - g) / d + 4; break;
    }
    h /= 6;
  }
  return `${Math.round(h * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
};

type ThemeColors = {
  background: string;
  foreground: string;
  card: string;
  "card-foreground": string;
  popover: string;
  "popover-foreground": string;
  primary: string;
  "primary-foreground": string;
  secondary: string;
  "secondary-foreground": string;
  muted: string;
  "muted-foreground": string;
  accent: string;
  "accent-foreground": string;
  destructive: string;
  "destructive-foreground": string;
  border: string;
  input: string;
  ring: string;
};

export type ColorScheme = {
  name: string;
  label: string;
  colors: {
    light: ThemeColors;
    dark: ThemeColors;
  };
};

export const colorSchemes: ColorScheme[] = [
  {
    name: 'COLOR_SCHEME_1',
    label: 'Indigo & Purple',
    colors: {
      light: {
        background: hexToHsl("#FFFFFF"),
        foreground: hexToHsl("#2D3748"),
        card: hexToHsl("#FFFFFF"),
        "card-foreground": hexToHsl("#2D3748"),
        popover: hexToHsl("#FFFFFF"),
        "popover-foreground": hexToHsl("#2D3748"),
        primary: hexToHsl("#5A67D8"),
        "primary-foreground": hexToHsl("#F7FAFC"),
        secondary: hexToHsl("#F7FAFC"),
        "secondary-foreground": hexToHsl("#2D3748"),
        muted: hexToHsl("#F7FAFC"),
        "muted-foreground": hexToHsl("#718096"),
        accent: hexToHsl("#805AD5"),
        "accent-foreground": hexToHsl("#F7FAFC"),
        destructive: hexToHsl("#E53E3E"),
        "destructive-foreground": hexToHsl("#F7FAFC"),
        border: hexToHsl("#E2E8F0"),
        input: hexToHsl("#E2E8F0"),
        ring: hexToHsl("#805AD5"),
      },
      dark: {
        background: hexToHsl("#1A202C"),
        foreground: hexToHsl("#F7FAFC"),
        card: hexToHsl("#1A202C"),
        "card-foreground": hexToHsl("#F7FAFC"),
        popover: hexToHsl("#1A202C"),
        "popover-foreground": hexToHsl("#F7FAFC"),
        primary: hexToHsl("#805AD5"),
        "primary-foreground": hexToHsl("#F7FAFC"),
        secondary: hexToHsl("#2D3748"),
        "secondary-foreground": hexToHsl("#F7FAFC"),
        muted: hexToHsl("#2D3748"),
        "muted-foreground": hexToHsl("#A0AEC0"),
        accent: hexToHsl("#5A67D8"),
        "accent-foreground": hexToHsl("#F7FAFC"),
        destructive: hexToHsl("#FC8181"),
        "destructive-foreground": hexToHsl("#1A202C"),
        border: hexToHsl("#2D3748"),
        input: hexToHsl("#2D3748"),
        ring: hexToHsl("#5A67D8"),
      },
    },
  },
  {
    name: 'COLOR_SCHEME_2',
    label: 'Green & Blue',
    colors: {
      light: {
        background: hexToHsl("#EBF4FA"),
        foreground: hexToHsl("#344454"),
        card: hexToHsl("#FFFFFF"),
        "card-foreground": hexToHsl("#344454"),
        popover: hexToHsl("#FFFFFF"),
        "popover-foreground": hexToHsl("#344454"),
        primary: hexToHsl("#05AD15"),
        "primary-foreground": hexToHsl("#FFFFFF"),
        secondary: hexToHsl("#D7E0E8"),
        "secondary-foreground": hexToHsl("#344454"),
        muted: hexToHsl("#D7E0E8"),
        "muted-foreground": hexToHsl("#6C7A89"),
        accent: hexToHsl("#58B0E3"),
        "accent-foreground": hexToHsl("#FFFFFF"),
        destructive: hexToHsl("#E53E3E"),
        "destructive-foreground": hexToHsl("#FFFFFF"),
        border: hexToHsl("#D7E0E8"),
        input: hexToHsl("#D7E0E8"),
        ring: hexToHsl("#05AD15"),
      },
      dark: {
        background: hexToHsl("#141C24"),
        foreground: hexToHsl("#EBF4FA"),
        card: hexToHsl("#1F2933"),
        "card-foreground": hexToHsl("#EBF4FA"),
        popover: hexToHsl("#1F2933"),
        "popover-foreground": hexToHsl("#EBF4FA"),
        primary: hexToHsl("#05AD15"),
        "primary-foreground": hexToHsl("#EBF4FA"),
        secondary: hexToHsl("#1F2933"),
        "secondary-foreground": hexToHsl("#EBF4FA"),
        muted: hexToHsl("#1F2933"),
        "muted-foreground": hexToHsl("#9AA5B1"),
        accent: hexToHsl("#58B0E3"),
        "accent-foreground": hexToHsl("#141C24"),
        destructive: hexToHsl("#FC8181"),
        "destructive-foreground": hexToHsl("#141C24"),
        border: hexToHsl("#1F2933"),
        input: hexToHsl("#1F2933"),
        ring: hexToHsl("#05AD15"),
      },
    },
  },
  {
    name: 'COLOR_SCHEME_3',
    label: 'Blue & Green',
    colors: {
      light: {
        background: hexToHsl("#F8FAFF"),
        foreground: hexToHsl("#09090B"),
        card: hexToHsl("#FFFFFF"),
        "card-foreground": hexToHsl("#09090B"),
        popover: hexToHsl("#FFFFFF"),
        "popover-foreground": hexToHsl("#09090B"),
        primary: hexToHsl("#3C84F6"),
        "primary-foreground": hexToHsl("#FFFFFF"),
        secondary: hexToHsl("#E3E5E8"),
        "secondary-foreground": hexToHsl("#09090B"),
        muted: hexToHsl("#E3E5E8"),
        "muted-foreground": hexToHsl("#71717A"),
        accent: hexToHsl("#06AD2E"),
        "accent-foreground": hexToHsl("#FFFFFF"),
        destructive: hexToHsl("#E53E3E"),
        "destructive-foreground": hexToHsl("#FFFFFF"),
        border: hexToHsl("#E3E5E8"),
        input: hexToHsl("#E3E5E8"),
        ring: hexToHsl("#06AD2E"),
      },
      dark: {
        background: hexToHsl("#09090B"),
        foreground: hexToHsl("#F8FAFF"),
        card: hexToHsl("#18181B"),
        "card-foreground": hexToHsl("#F8FAFF"),
        popover: hexToHsl("#18181B"),
        "popover-foreground": hexToHsl("#F8FAFF"),
        primary: hexToHsl("#3C84F6"),
        "primary-foreground": hexToHsl("#F8FAFF"),
        secondary: hexToHsl("#222B36"),
        "secondary-foreground": hexToHsl("#F8FAFF"),
        muted: hexToHsl("#222B36"),
        "muted-foreground": hexToHsl("#A1A1AA"),
        accent: hexToHsl("#06AD2E"),
        "accent-foreground": hexToHsl("#F8FAFF"),
        destructive: hexToHsl("#FC8181"),
        "destructive-foreground": hexToHsl("#09090B"),
        border: hexToHsl("#222B36"),
        input: hexToHsl("#222B36"),
        ring: hexToHsl("#06AD2E"),
      },
    },
  },
  {
    name: 'COLOR_SCHEME_4',
    label: 'Purple & Pink',
    colors: {
      light: {
        background: hexToHsl("#FFFFFF"),
        foreground: hexToHsl("#333333"),
        card: hexToHsl("#FFFFFF"),
        "card-foreground": hexToHsl("#333333"),
        popover: hexToHsl("#FFFFFF"),
        "popover-foreground": hexToHsl("#333333"),
        primary: hexToHsl("#8B5CF6"),
        "primary-foreground": hexToHsl("#FFFFFF"),
        secondary: hexToHsl("#F3F4F6"),
        "secondary-foreground": hexToHsl("#333333"),
        muted: hexToHsl("#F3F4F6"),
        "muted-foreground": hexToHsl("#777777"),
        accent: hexToHsl("#EC4899"),
        "accent-foreground": hexToHsl("#FFFFFF"),
        destructive: hexToHsl("#EF4444"),
        "destructive-foreground": hexToHsl("#FFFFFF"),
        border: hexToHsl("#DDDDDD"),
        input: hexToHsl("#DDDDDD"),
        ring: hexToHsl("#EC4899"),
      },
      dark: {
        background: hexToHsl("#1E1E2E"),
        foreground: hexToHsl("#F0F0F0"),
        card: hexToHsl("#25253A"),
        "card-foreground": hexToHsl("#F0F0F0"),
        popover: hexToHsl("#25253A"),
        "popover-foreground": hexToHsl("#F0F0F0"),
        primary: hexToHsl("#A78BFA"),
        "primary-foreground": hexToHsl("#1E1E2E"),
        secondary: hexToHsl("#3A3A4C"),
        "secondary-foreground": hexToHsl("#F0F0F0"),
        muted: hexToHsl("#3A3A4C"),
        "muted-foreground": hexToHsl("#B0B0B0"),
        accent: hexToHsl("#F472B6"),
        "accent-foreground": hexToHsl("#1E1E2E"),
        destructive: hexToHsl("#F87171"),
        "destructive-foreground": hexToHsl("#1E1E2E"),
        border: hexToHsl("#3A3A4C"),
        input: hexToHsl("#3A3A4C"),
        ring: hexToHsl("#F472B6"),
      },
    },
  },
  {
    name: 'COLOR_SCHEME_5',
    label: 'Orange & Gold',
    colors: {
      light: {
        background: hexToHsl("#FCFBF5"),
        foreground: hexToHsl("#5C4B4B"),
        card: hexToHsl("#FFFFFF"),
        "card-foreground": hexToHsl("#5C4B4B"),
        popover: hexToHsl("#FFFFFF"),
        "popover-foreground": hexToHsl("#5C4B4B"),
        primary: hexToHsl("#E77727"),
        "primary-foreground": hexToHsl("#FFFFFF"),
        secondary: hexToHsl("#EFEAE2"),
        "secondary-foreground": hexToHsl("#5C4B4B"),
        muted: hexToHsl("#EFEAE2"),
        "muted-foreground": hexToHsl("#8B8077"),
        accent: hexToHsl("#B3A16D"),
        "accent-foreground": hexToHsl("#FFFFFF"),
        destructive: hexToHsl("#D9534F"),
        "destructive-foreground": hexToHsl("#FFFFFF"),
        border: hexToHsl("#EFEAE2"),
        input: hexToHsl("#EFEAE2"),
        ring: hexToHsl("#B3A16D"),
      },
      dark: {
        background: hexToHsl("#362C2C"),
        foreground: hexToHsl("#FDF8F0"),
        card: hexToHsl("#4F4040"),
        "card-foreground": hexToHsl("#FDF8F0"),
        popover: hexToHsl("#4F4040"),
        "popover-foreground": hexToHsl("#FDF8F0"),
        primary: hexToHsl("#FF9944"),
        "primary-foreground": hexToHsl("#362C2C"),
        secondary: hexToHsl("#4F4040"),
        "secondary-foreground": hexToHsl("#FDF8F0"),
        muted: hexToHsl("#4F4040"),
        "muted-foreground": hexToHsl("#C4B9B0"),
        accent: hexToHsl("#D4C29D"),
        "accent-foreground": hexToHsl("#362C2C"),
        destructive: hexToHsl("#F98B87"),
        "destructive-foreground": hexToHsl("#362C2C"),
        border: hexToHsl("#4F4040"),
        input: hexToHsl("#4F4040"),
        ring: hexToHsl("#D4C29D"),
      },
    },
  },
  {
    name: 'COLOR_SCHEME_6',
    label: 'Professional Blue',
    colors: {
      light: {
        background: hexToHsl("#F8F8F8"),
        foreground: hexToHsl("#2D3748"),
        card: hexToHsl("#FFFFFF"),
        "card-foreground": hexToHsl("#2D3748"),
        popover: hexToHsl("#FFFFFF"),
        "popover-foreground": hexToHsl("#2D3748"),
        primary: hexToHsl("#3B82F6"),
        "primary-foreground": hexToHsl("#FFFFFF"),
        secondary: hexToHsl("#E2E8F0"),
        "secondary-foreground": hexToHsl("#2D3748"),
        muted: hexToHsl("#E2E8F0"),
        "muted-foreground": hexToHsl("#718096"),
        accent: hexToHsl("#10B981"),
        "accent-foreground": hexToHsl("#FFFFFF"),
        destructive: hexToHsl("#EF4444"),
        "destructive-foreground": hexToHsl("#FFFFFF"),
        border: hexToHsl("#E2E8F0"),
        input: hexToHsl("#E2E8F0"),
        ring: hexToHsl("#10B981"),
      },
      dark: {
        background: hexToHsl("#1A202C"),
        foreground: hexToHsl("#E2E8F0"),
        card: hexToHsl("#2D3748"),
        "card-foreground": hexToHsl("#E2E8F0"),
        popover: hexToHsl("#2D3748"),
        "popover-foreground": hexToHsl("#E2E8F0"),
        primary: hexToHsl("#63B3ED"),
        "primary-foreground": hexToHsl("#1A202C"),
        secondary: hexToHsl("#2D3748"),
        "secondary-foreground": hexToHsl("#E2E8F0"),
        muted: hexToHsl("#2D3748"),
        "muted-foreground": hexToHsl("#A0AEC0"),
        accent: hexToHsl("#48BB78"),
        "accent-foreground": hexToHsl("#1A202C"),
        destructive: hexToHsl("#F87171"),
        "destructive-foreground": hexToHsl("#1A202C"),
        border: hexToHsl("#2D3748"),
        input: hexToHsl("#2D3748"),
        ring: hexToHsl("#48BB78"),
      },
    },
  },
  {
    name: 'COLOR_SCHEME_7',
    label: 'Slate & Rose',
    colors: {
      light: {
        background: hexToHsl("#f9fafb"),
        foreground: hexToHsl("#374151"),
        card: hexToHsl("#ffffff"),
        "card-foreground": hexToHsl("#374151"),
        popover: hexToHsl("#ffffff"),
        "popover-foreground": hexToHsl("#374151"),
        primary: hexToHsl("#4b5563"),
        "primary-foreground": hexToHsl("#f9fafb"),
        secondary: hexToHsl("#f3f4f6"),
        "secondary-foreground": hexToHsl("#374151"),
        muted: hexToHsl("#f3f4f6"),
        "muted-foreground": hexToHsl("#6b7280"),
        accent: hexToHsl("#fb7185"),
        "accent-foreground": hexToHsl("#1f2937"),
        destructive: hexToHsl("#ef4444"),
        "destructive-foreground": hexToHsl("#f9fafb"),
        border: hexToHsl("#e5e7eb"),
        input: hexToHsl("#e5e7eb"),
        ring: hexToHsl("#fb7185"),
      },
      dark: {
        background: hexToHsl("#111827"),
        foreground: hexToHsl("#d1d5db"),
        card: hexToHsl("#1f2937"),
        "card-foreground": hexToHsl("#d1d5db"),
        popover: hexToHsl("#1f2937"),
        "popover-foreground": hexToHsl("#d1d5db"),
        primary: hexToHsl("#9ca3af"),
        "primary-foreground": hexToHsl("#111827"),
        secondary: hexToHsl("#374151"),
        "secondary-foreground": hexToHsl("#d1d5db"),
        muted: hexToHsl("#374151"),
        "muted-foreground": hexToHsl("#9ca3af"),
        accent: hexToHsl("#fb7185"),
        "accent-foreground": hexToHsl("#111827"),
        destructive: hexToHsl("#f87171"),
        "destructive-foreground": hexToHsl("#111827"),
        border: hexToHsl("#374151"),
        input: hexToHsl("#374151"),
        ring: hexToHsl("#fb7185"),
      },
    },
  },
  {
    name: 'COLOR_SCHEME_8',
    label: 'Teal & Cyan',
    colors: {
      light: {
        background: hexToHsl("#f0f9ff"),
        foreground: hexToHsl("#0c4a6e"),
        card: hexToHsl("#ffffff"),
        "card-foreground": hexToHsl("#0c4a6e"),
        popover: hexToHsl("#ffffff"),
        "popover-foreground": hexToHsl("#0c4a6e"),
        primary: hexToHsl("#0891b2"),
        "primary-foreground": hexToHsl("#ffffff"),
        secondary: hexToHsl("#e0f2fe"),
        "secondary-foreground": hexToHsl("#0c4a6e"),
        muted: hexToHsl("#e0f2fe"),
        "muted-foreground": hexToHsl("#387896"),
        accent: hexToHsl("#22d3ee"),
        "accent-foreground": hexToHsl("#0c4a6e"),
        destructive: hexToHsl("#ef4444"),
        "destructive-foreground": hexToHsl("#ffffff"),
        border: hexToHsl("#bae6fd"),
        input: hexToHsl("#bae6fd"),
        ring: hexToHsl("#22d3ee"),
      },
      dark: {
        background: hexToHsl("#082f49"),
        foreground: hexToHsl("#e0f2fe"),
        card: hexToHsl("#07273d"),
        "card-foreground": hexToHsl("#e0f2fe"),
        popover: hexToHsl("#07273d"),
        "popover-foreground": hexToHsl("#e0f2fe"),
        primary: hexToHsl("#22d3ee"),
        "primary-foreground": hexToHsl("#082f49"),
        secondary: hexToHsl("#0c4a6e"),
        "secondary-foreground": hexToHsl("#e0f2fe"),
        muted: hexToHsl("#0c4a6e"),
        "muted-foreground": hexToHsl("#7dd3fc"),
        accent: hexToHsl("#67e8f9"),
        "accent-foreground": hexToHsl("#082f49"),
        destructive: hexToHsl("#f87171"),
        "destructive-foreground": hexToHsl("#082f49"),
        border: hexToHsl("#0c4a6e"),
        input: hexToHsl("#0c4a6e"),
        ring: hexToHsl("#67e8f9"),
      },
    },
  },
  {
    name: 'COLOR_SCHEME_9',
    label: 'Cherry Blossom',
    colors: {
      light: {
        background: hexToHsl("#fff1f2"),
        foreground: hexToHsl("#881337"),
        card: hexToHsl("#ffffff"),
        "card-foreground": hexToHsl("#881337"),
        popover: hexToHsl("#ffffff"),
        "popover-foreground": hexToHsl("#881337"),
        primary: hexToHsl("#e11d48"),
        "primary-foreground": hexToHsl("#ffffff"),
        secondary: hexToHsl("#ffe4e6"),
        "secondary-foreground": hexToHsl("#881337"),
        muted: hexToHsl("#ffe4e6"),
        "muted-foreground": hexToHsl("#be123c"),
        accent: hexToHsl("#f43f5e"),
        "accent-foreground": hexToHsl("#ffffff"),
        destructive: hexToHsl("#ef4444"),
        "destructive-foreground": hexToHsl("#ffffff"),
        border: hexToHsl("#fecdd3"),
        input: hexToHsl("#fecdd3"),
        ring: hexToHsl("#f43f5e"),
      },
      dark: {
        background: hexToHsl("#5f0a21"),
        foreground: hexToHsl("#ffe4e6"),
        card: hexToHsl("#881337"),
        "card-foreground": hexToHsl("#ffe4e6"),
        popover: hexToHsl("#881337"),
        "popover-foreground": hexToHsl("#ffe4e6"),
        primary: hexToHsl("#f9a8d4"),
        "primary-foreground": hexToHsl("#5f0a21"),
        secondary: hexToHsl("#be185d"),
        "secondary-foreground": hexToHsl("#ffe4e6"),
        muted: hexToHsl("#be185d"),
        "muted-foreground": hexToHsl("#fbcfe8"),
        accent: hexToHsl("#f472b6"),
        "accent-foreground": hexToHsl("#5f0a21"),
        destructive: hexToHsl("#f87171"),
        "destructive-foreground": hexToHsl("#5f0a21"),
        border: hexToHsl("#be185d"),
        input: hexToHsl("#be185d"),
        ring: hexToHsl("#f472b6"),
      },
    },
  },
  {
    name: 'COLOR_SCHEME_10',
    label: 'Cyberpunk Lime',
    colors: {
      light: {
        background: hexToHsl("#f7fee7"),
        foreground: hexToHsl("#365314"),
        card: hexToHsl("#ffffff"),
        "card-foreground": hexToHsl("#365314"),
        popover: hexToHsl("#ffffff"),
        "popover-foreground": hexToHsl("#365314"),
        primary: hexToHsl("#84cc16"),
        "primary-foreground": hexToHsl("#1a2e05"),
        secondary: hexToHsl("#dcfce7"),
        "secondary-foreground": hexToHsl("#365314"),
        muted: hexToHsl("#dcfce7"),
        "muted-foreground": hexToHsl("#4d7c0f"),
        accent: hexToHsl("#a3e635"),
        "accent-foreground": hexToHsl("#1a2e05"),
        destructive: hexToHsl("#ef4444"),
        "destructive-foreground": hexToHsl("#ffffff"),
        border: hexToHsl("#bbf7d0"),
        input: hexToHsl("#bbf7d0"),
        ring: hexToHsl("#a3e635"),
      },
      dark: {
        background: hexToHsl("#1a2e05"),
        foreground: hexToHsl("#dcfce7"),
        card: hexToHsl("#2a420b"),
        "card-foreground": hexToHsl("#dcfce7"),
        popover: hexToHsl("#2a420b"),
        "popover-foreground": hexToHsl("#dcfce7"),
        primary: hexToHsl("#a3e635"),
        "primary-foreground": hexToHsl("#1a2e05"),
        secondary: hexToHsl("#365314"),
        "secondary-foreground": hexToHsl("#dcfce7"),
        muted: hexToHsl("#365314"),
        "muted-foreground": hexToHsl("#a3e635"),
        accent: hexToHsl("#bef264"),
        "accent-foreground": hexToHsl("#1a2e05"),
        destructive: hexToHsl("#f87171"),
        "destructive-foreground": hexToHsl("#1a2e05"),
        border: hexToHsl("#365314"),
        input: hexToHsl("#365314"),
        ring: hexToHsl("#bef264"),
      },
    },
  },
  {
    name: 'COLOR_SCHEME_11',
    label: 'Sunset Orange',
    colors: {
      light: {
        background: hexToHsl("#fff7ed"),
        foreground: hexToHsl("#7c2d12"),
        card: hexToHsl("#ffffff"),
        "card-foreground": hexToHsl("#7c2d12"),
        popover: hexToHsl("#ffffff"),
        "popover-foreground": hexToHsl("#7c2d12"),
        primary: hexToHsl("#f97316"),
        "primary-foreground": hexToHsl("#ffffff"),
        secondary: hexToHsl("#ffedd5"),
        "secondary-foreground": hexToHsl("#7c2d12"),
        muted: hexToHsl("#ffedd5"),
        "muted-foreground": hexToHsl("#9a3412"),
        accent: hexToHsl("#fb923c"),
        "accent-foreground": hexToHsl("#7c2d12"),
        destructive: hexToHsl("#ef4444"),
        "destructive-foreground": hexToHsl("#ffffff"),
        border: hexToHsl("#fed7aa"),
        input: hexToHsl("#fed7aa"),
        ring: hexToHsl("#fb923c"),
      },
      dark: {
        background: hexToHsl("#431407"),
        foreground: hexToHsl("#ffedd5"),
        card: hexToHsl("#5f270e"),
        "card-foreground": hexToHsl("#ffedd5"),
        popover: hexToHsl("#5f270e"),
        "popover-foreground": hexToHsl("#ffedd5"),
        primary: hexToHsl("#fb923c"),
        "primary-foreground": hexToHsl("#431407"),
        secondary: hexToHsl("#7c2d12"),
        "secondary-foreground": hexToHsl("#ffedd5"),
        muted: hexToHsl("#7c2d12"),
        "muted-foreground": hexToHsl("#fdba74"),
        accent: hexToHsl("#f97316"),
        "accent-foreground": hexToHsl("#ffedd5"),
        destructive: hexToHsl("#f87171"),
        "destructive-foreground": hexToHsl("#431407"),
        border: hexToHsl("#7c2d12"),
        input: hexToHsl("#7c2d12"),
        ring: hexToHsl("#f97316"),
      },
    },
  },
  {
    name: 'COLOR_SCHEME_12',
    label: 'Oceanic Blue',
    colors: {
      light: {
        background: hexToHsl("#f0faff"),
        foreground: hexToHsl("#075985"),
        card: hexToHsl("#ffffff"),
        "card-foreground": hexToHsl("#075985"),
        popover: hexToHsl("#ffffff"),
        "popover-foreground": hexToHsl("#075985"),
        primary: hexToHsl("#0ea5e9"),
        "primary-foreground": hexToHsl("#ffffff"),
        secondary: hexToHsl("#e0f2fe"),
        "secondary-foreground": hexToHsl("#075985"),
        muted: hexToHsl("#e0f2fe"),
        "muted-foreground": hexToHsl("#0c4a6e"),
        accent: hexToHsl("#38bdf8"),
        "accent-foreground": hexToHsl("#075985"),
        destructive: hexToHsl("#ef4444"),
        "destructive-foreground": hexToHsl("#ffffff"),
        border: hexToHsl("#bae6fd"),
        input: hexToHsl("#bae6fd"),
        ring: hexToHsl("#38bdf8"),
      },
      dark: {
        background: hexToHsl("#0c2e42"),
        foreground: hexToHsl("#e0f2fe"),
        card: hexToHsl("#083344"),
        "card-foreground": hexToHsl("#e0f2fe"),
        popover: hexToHsl("#083344"),
        "popover-foreground": hexToHsl("#e0f2fe"),
        primary: hexToHsl("#38bdf8"),
        "primary-foreground": hexToHsl("#0c2e42"),
        secondary: hexToHsl("#075985"),
        "secondary-foreground": hexToHsl("#e0f2fe"),
        muted: hexToHsl("#075985"),
        "muted-foreground": hexToHsl("#7dd3fc"),
        accent: hexToHsl("#0ea5e9"),
        "accent-foreground": hexToHsl("#e0f2fe"),
        destructive: hexToHsl("#f87171"),
        "destructive-foreground": hexToHsl("#0c2e42"),
        border: hexToHsl("#075985"),
        input: hexToHsl("#075985"),
        ring: hexToHsl("#0ea5e9"),
      },
    },
  },
  {
    name: 'COLOR_SCHEME_13',
    label: 'Forest Emerald',
    colors: {
      light: {
        background: hexToHsl("#f0fdf4"),
        foreground: hexToHsl("#14532d"),
        card: hexToHsl("#ffffff"),
        "card-foreground": hexToHsl("#14532d"),
        popover: hexToHsl("#ffffff"),
        "popover-foreground": hexToHsl("#14532d"),
        primary: hexToHsl("#10b981"),
        "primary-foreground": hexToHsl("#ffffff"),
        secondary: hexToHsl("#dcfce7"),
        "secondary-foreground": hexToHsl("#14532d"),
        muted: hexToHsl("#dcfce7"),
        "muted-foreground": hexToHsl("#166534"),
        accent: hexToHsl("#34d399"),
        "accent-foreground": hexToHsl("#14532d"),
        destructive: hexToHsl("#ef4444"),
        "destructive-foreground": hexToHsl("#ffffff"),
        border: hexToHsl("#bbf7d0"),
        input: hexToHsl("#bbf7d0"),
        ring: hexToHsl("#34d399"),
      },
      dark: {
        background: hexToHsl("#052e16"),
        foreground: hexToHsl("#dcfce7"),
        card: hexToHsl("#064e3b"),
        "card-foreground": hexToHsl("#dcfce7"),
        popover: hexToHsl("#064e3b"),
        "popover-foreground": hexToHsl("#dcfce7"),
        primary: hexToHsl("#34d399"),
        "primary-foreground": hexToHsl("#052e16"),
        secondary: hexToHsl("#14532d"),
        "secondary-foreground": hexToHsl("#dcfce7"),
        muted: hexToHsl("#14532d"),
        "muted-foreground": hexToHsl("#6ee7b7"),
        accent: hexToHsl("#10b981"),
        "accent-foreground": hexToHsl("#dcfce7"),
        destructive: hexToHsl("#f87171"),
        "destructive-foreground": hexToHsl("#052e16"),
        border: hexToHsl("#14532d"),
        input: hexToHsl("#14532d"),
        ring: hexToHsl("#10b981"),
      },
    },
  },
  {
    name: 'COLOR_SCHEME_14',
    label: 'Royal Purple',
    colors: {
      light: {
        background: hexToHsl("#fbf5ff"),
        foreground: hexToHsl("#5b21b6"),
        card: hexToHsl("#ffffff"),
        "card-foreground": hexToHsl("#5b21b6"),
        popover: hexToHsl("#ffffff"),
        "popover-foreground": hexToHsl("#5b21b6"),
        primary: hexToHsl("#9333ea"),
        "primary-foreground": hexToHsl("#ffffff"),
        secondary: hexToHsl("#f3e8ff"),
        "secondary-foreground": hexToHsl("#5b21b6"),
        muted: hexToHsl("#f3e8ff"),
        "muted-foreground": hexToHsl("#7e22ce"),
        accent: hexToHsl("#a855f7"),
        "accent-foreground": hexToHsl("#ffffff"),
        destructive: hexToHsl("#ef4444"),
        "destructive-foreground": hexToHsl("#ffffff"),
        border: hexToHsl("#e9d5ff"),
        input: hexToHsl("#e9d5ff"),
        ring: hexToHsl("#a855f7"),
      },
      dark: {
        background: hexToHsl("#2e1065"),
        foreground: hexToHsl("#f3e8ff"),
        card: hexToHsl("#4c1d95"),
        "card-foreground": hexToHsl("#f3e8ff"),
        popover: hexToHsl("#4c1d95"),
        "popover-foreground": hexToHsl("#f3e8ff"),
        primary: hexToHsl("#c084fc"),
        "primary-foreground": hexToHsl("#2e1065"),
        secondary: hexToHsl("#5b21b6"),
        "secondary-foreground": hexToHsl("#f3e8ff"),
        muted: hexToHsl("#5b21b6"),
        "muted-foreground": hexToHsl("#d8b4fe"),
        accent: hexToHsl("#a855f7"),
        "accent-foreground": hexToHsl("#f3e8ff"),
        destructive: hexToHsl("#f87171"),
        "destructive-foreground": hexToHsl("#2e1065"),
        border: hexToHsl("#5b21b6"),
        input: hexToHsl("#5b21b6"),
        ring: hexToHsl("#a855f7"),
      },
    },
  },
  {
    name: 'COLOR_SCHEME_15',
    label: 'Monochrome Gray',
    colors: {
      light: {
        background: hexToHsl("#ffffff"),
        foreground: hexToHsl("#171717"),
        card: hexToHsl("#fafafa"),
        "card-foreground": hexToHsl("#171717"),
        popover: hexToHsl("#ffffff"),
        "popover-foreground": hexToHsl("#171717"),
        primary: hexToHsl("#525252"),
        "primary-foreground": hexToHsl("#ffffff"),
        secondary: hexToHsl("#e5e5e5"),
        "secondary-foreground": hexToHsl("#171717"),
        muted: hexToHsl("#f5f5f5"),
        "muted-foreground": hexToHsl("#737373"),
        accent: hexToHsl("#a3a3a3"),
        "accent-foreground": hexToHsl("#171717"),
        destructive: hexToHsl("#ef4444"),
        "destructive-foreground": hexToHsl("#ffffff"),
        border: hexToHsl("#d4d4d4"),
        input: hexToHsl("#d4d4d4"),
        ring: hexToHsl("#a3a3a3"),
      },
      dark: {
        background: hexToHsl("#0a0a0a"),
        foreground: hexToHsl("#fafafa"),
        card: hexToHsl("#171717"),
        "card-foreground": hexToHsl("#fafafa"),
        popover: hexToHsl("#171717"),
        "popover-foreground": hexToHsl("#fafafa"),
        primary: hexToHsl("#a3a3a3"),
        "primary-foreground": hexToHsl("#0a0a0a"),
        secondary: hexToHsl("#262626"),
        "secondary-foreground": hexToHsl("#fafafa"),
        muted: hexToHsl("#262626"),
        "muted-foreground": hexToHsl("#a3a3a3"),
        accent: hexToHsl("#737373"),
        "accent-foreground": hexToHsl("#fafafa"),
        destructive: hexToHsl("#f87171"),
        "destructive-foreground": hexToHsl("#0a0a0a"),
        border: hexToHsl("#262626"),
        input: hexToHsl("#262626"),
        ring: hexToHsl("#737373"),
      },
    },
  },
  {
    name: 'COLOR_SCHEME_16',
    label: 'Rose Gold',
    colors: {
      light: {
        background: hexToHsl("#fffbfa"),
        foreground: hexToHsl("#854d0e"),
        card: hexToHsl("#ffffff"),
        "card-foreground": hexToHsl("#854d0e"),
        popover: hexToHsl("#ffffff"),
        "popover-foreground": hexToHsl("#854d0e"),
        primary: hexToHsl("#e11d48"),
        "primary-foreground": hexToHsl("#ffffff"),
        secondary: hexToHsl("#fef3c7"),
        "secondary-foreground": hexToHsl("#854d0e"),
        muted: hexToHsl("#fffbeb"),
        "muted-foreground": hexToHsl("#b45309"),
        accent: hexToHsl("#fbbf24"),
        "accent-foreground": hexToHsl("#854d0e"),
        destructive: hexToHsl("#ef4444"),
        "destructive-foreground": hexToHsl("#ffffff"),
        border: hexToHsl("#fde68a"),
        input: hexToHsl("#fde68a"),
        ring: hexToHsl("#fbbf24"),
      },
      dark: {
        background: hexToHsl("#45230b"),
        foreground: hexToHsl("#fffbeb"),
        card: hexToHsl("#573a1a"),
        "card-foreground": hexToHsl("#fffbeb"),
        popover: hexToHsl("#573a1a"),
        "popover-foreground": hexToHsl("#fffbeb"),
        primary: hexToHsl("#f9a8d4"),
        "primary-foreground": hexToHsl("#45230b"),
        secondary: hexToHsl("#854d0e"),
        "secondary-foreground": hexToHsl("#fffbeb"),
        muted: hexToHsl("#854d0e"),
        "muted-foreground": hexToHsl("#fef3c7"),
        accent: hexToHsl("#fcd34d"),
        "accent-foreground": hexToHsl("#45230b"),
        destructive: hexToHsl("#f87171"),
        "destructive-foreground": hexToHsl("#45230b"),
        border: hexToHsl("#854d0e"),
        input: hexToHsl("#854d0e"),
        ring: hexToHsl("#fcd34d"),
      },
    },
  },
  {
    name: 'COLOR_SCHEME_17',
    label: 'Minty Fresh',
    colors: {
      light: {
        background: hexToHsl("#fafff5"),
        foreground: hexToHsl("#166534"),
        card: hexToHsl("#ffffff"),
        "card-foreground": hexToHsl("#166534"),
        popover: hexToHsl("#ffffff"),
        "popover-foreground": hexToHsl("#166534"),
        primary: hexToHsl("#22c55e"),
        "primary-foreground": hexToHsl("#ffffff"),
        secondary: hexToHsl("#f0fdf4"),
        "secondary-foreground": hexToHsl("#166534"),
        muted: hexToHsl("#f0fdf4"),
        "muted-foreground": hexToHsl("#15803d"),
        accent: hexToHsl("#4ade80"),
        "accent-foreground": hexToHsl("#166534"),
        destructive: hexToHsl("#ef4444"),
        "destructive-foreground": hexToHsl("#ffffff"),
        border: hexToHsl("#dcfce7"),
        input: hexToHsl("#dcfce7"),
        ring: hexToHsl("#4ade80"),
      },
      dark: {
        background: hexToHsl("#0d3d1f"),
        foreground: hexToHsl("#f0fdf4"),
        card: hexToHsl("#14532d"),
        "card-foreground": hexToHsl("#f0fdf4"),
        popover: hexToHsl("#14532d"),
        "popover-foreground": hexToHsl("#f0fdf4"),
        primary: hexToHsl("#4ade80"),
        "primary-foreground": hexToHsl("#0d3d1f"),
        secondary: hexToHsl("#166534"),
        "secondary-foreground": hexToHsl("#f0fdf4"),
        muted: hexToHsl("#166534"),
        "muted-foreground": hexToHsl("#86efac"),
        accent: hexToHsl("#22c55e"),
        "accent-foreground": hexToHsl("#f0fdf4"),
        destructive: hexToHsl("#f87171"),
        "destructive-foreground": hexToHsl("#0d3d1f"),
        border: hexToHsl("#166534"),
        input: hexToHsl("#166534"),
        ring: hexToHsl("#22c55e"),
      },
    },
  },
  {
    name: 'COLOR_SCHEME_18',
    label: 'Crimson & Cream',
    colors: {
      light: {
        background: hexToHsl("#fff8f8"),
        foreground: hexToHsl("#991b1b"),
        card: hexToHsl("#ffffff"),
        "card-foreground": hexToHsl("#991b1b"),
        popover: hexToHsl("#ffffff"),
        "popover-foreground": hexToHsl("#991b1b"),
        primary: hexToHsl("#dc2626"),
        "primary-foreground": hexToHsl("#ffffff"),
        secondary: hexToHsl("#fee2e2"),
        "secondary-foreground": hexToHsl("#991b1b"),
        muted: hexToHsl("#fee2e2"),
        "muted-foreground": hexToHsl("#b91c1c"),
        accent: hexToHsl("#ef4444"),
        "accent-foreground": hexToHsl("#ffffff"),
        destructive: hexToHsl("#ef4444"),
        "destructive-foreground": hexToHsl("#ffffff"),
        border: hexToHsl("#fecaca"),
        input: hexToHsl("#fecaca"),
        ring: hexToHsl("#ef4444"),
      },
      dark: {
        background: hexToHsl("#450a0a"),
        foreground: hexToHsl("#fee2e2"),
        card: hexToHsl("#7f1d1d"),
        "card-foreground": hexToHsl("#fee2e2"),
        popover: hexToHsl("#7f1d1d"),
        "popover-foreground": hexToHsl("#fee2e2"),
        primary: hexToHsl("#f87171"),
        "primary-foreground": hexToHsl("#450a0a"),
        secondary: hexToHsl("#991b1b"),
        "secondary-foreground": hexToHsl("#fee2e2"),
        muted: hexToHsl("#991b1b"),
        "muted-foreground": hexToHsl("#fca5a5"),
        accent: hexToHsl("#ef4444"),
        "accent-foreground": hexToHsl("#fee2e2"),
        destructive: hexToHsl("#f87171"),
        "destructive-foreground": hexToHsl("#450a0a"),
        border: hexToHsl("#991b1b"),
        input: hexToHsl("#991b1b"),
        ring: hexToHsl("#ef4444"),
      },
    },
  },
  {
    name: 'COLOR_SCHEME_19',
    label: 'Coffee & Caramel',
    colors: {
      light: {
        background: hexToHsl("#fdfaf6"),
        foreground: hexToHsl("#78350f"),
        card: hexToHsl("#ffffff"),
        "card-foreground": hexToHsl("#78350f"),
        popover: hexToHsl("#ffffff"),
        "popover-foreground": hexToHsl("#78350f"),
        primary: hexToHsl("#d97706"),
        "primary-foreground": hexToHsl("#ffffff"),
        secondary: hexToHsl("#fef3c7"),
        "secondary-foreground": hexToHsl("#78350f"),
        muted: hexToHsl("#fef3c7"),
        "muted-foreground": hexToHsl("#92400e"),
        accent: hexToHsl("#f59e0b"),
        "accent-foreground": hexToHsl("#78350f"),
        destructive: hexToHsl("#ef4444"),
        "destructive-foreground": hexToHsl("#ffffff"),
        border: hexToHsl("#fde68a"),
        input: hexToHsl("#fde68a"),
        ring: hexToHsl("#f59e0b"),
      },
      dark: {
        background: hexToHsl("#422006"),
        foreground: hexToHsl("#fef3c7"),
        card: hexToHsl("#573a1a"),
        "card-foreground": hexToHsl("#fef3c7"),
        popover: hexToHsl("#573a1a"),
        "popover-foreground": hexToHsl("#fef3c7"),
        primary: hexToHsl("#f59e0b"),
        "primary-foreground": hexToHsl("#422006"),
        secondary: hexToHsl("#78350f"),
        "secondary-foreground": hexToHsl("#fef3c7"),
        muted: hexToHsl("#78350f"),
        "muted-foreground": hexToHsl("#fcd34d"),
        accent: hexToHsl("#d97706"),
        "accent-foreground": hexToHsl("#fef3c7"),
        destructive: hexToHsl("#f87171"),
        "destructive-foreground": hexToHsl("#422006"),
        border: hexToHsl("#78350f"),
        input: hexToHsl("#78350f"),
        ring: hexToHsl("#d97706"),
      },
    },
  },
  {
    name: 'COLOR_SCHEME_20',
    label: 'Electric Blue',
    colors: {
      light: {
        background: hexToHsl("#f5faff"),
        foreground: hexToHsl("#1e40af"),
        card: hexToHsl("#ffffff"),
        "card-foreground": hexToHsl("#1e40af"),
        popover: hexToHsl("#ffffff"),
        "popover-foreground": hexToHsl("#1e40af"),
        primary: hexToHsl("#3b82f6"),
        "primary-foreground": hexToHsl("#ffffff"),
        secondary: hexToHsl("#dbeafe"),
        "secondary-foreground": hexToHsl("#1e40af"),
        muted: hexToHsl("#dbeafe"),
        "muted-foreground": hexToHsl("#1d4ed8"),
        accent: hexToHsl("#60a5fa"),
        "accent-foreground": hexToHsl("#1e40af"),
        destructive: hexToHsl("#ef4444"),
        "destructive-foreground": hexToHsl("#ffffff"),
        border: hexToHsl("#bfdbfe"),
        input: hexToHsl("#bfdbfe"),
        ring: hexToHsl("#60a5fa"),
      },
      dark: {
        background: hexToHsl("#1e293b"),
        foreground: hexToHsl("#dbeafe"),
        card: hexToHsl("#1e3a8a"),
        "card-foreground": hexToHsl("#dbeafe"),
        popover: hexToHsl("#1e3a8a"),
        "popover-foreground": hexToHsl("#dbeafe"),
        primary: hexToHsl("#60a5fa"),
        "primary-foreground": hexToHsl("#1e293b"),
        secondary: hexToHsl("#1e40af"),
        "secondary-foreground": hexToHsl("#dbeafe"),
        muted: hexToHsl("#1e40af"),
        "muted-foreground": hexToHsl("#93c5fd"),
        accent: hexToHsl("#3b82f6"),
        "accent-foreground": hexToHsl("#dbeafe"),
        destructive: hexToHsl("#f87171"),
        "destructive-foreground": hexToHsl("#1e293b"),
        border: hexToHsl("#1e40af"),
        input: hexToHsl("#1e40af"),
        ring: hexToHsl("#3b82f6"),
      },
    },
  },
  {
    name: 'COLOR_SCHEME_21',
    label: 'Lavender Bliss',
    colors: {
        light: {
            background: hexToHsl("#F5F3FF"),
            foreground: hexToHsl("#4C1D95"),
            card: hexToHsl("#FFFFFF"),
            "card-foreground": hexToHsl("#4C1D95"),
            popover: hexToHsl("#FFFFFF"),
            "popover-foreground": hexToHsl("#4C1D95"),
            primary: hexToHsl("#8B5CF6"),
            "primary-foreground": hexToHsl("#FFFFFF"),
            secondary: hexToHsl("#EDE9FE"),
            "secondary-foreground": hexToHsl("#4C1D95"),
            muted: hexToHsl("#EDE9FE"),
            "muted-foreground": hexToHsl("#6D28D9"),
            accent: hexToHsl("#A78BFA"),
            "accent-foreground": hexToHsl("#4C1D95"),
            destructive: hexToHsl("#EF4444"),
            "destructive-foreground": hexToHsl("#FFFFFF"),
            border: hexToHsl("#DDD6FE"),
            input: hexToHsl("#DDD6FE"),
            ring: hexToHsl("#A78BFA"),
        },
        dark: {
            background: hexToHsl("#2E1065"),
            foreground: hexToHsl("#EDE9FE"),
            card: hexToHsl("#4C1D95"),
            "card-foreground": hexToHsl("#EDE9FE"),
            popover: hexToHsl("#4C1D95"),
            "popover-foreground": hexToHsl("#EDE9FE"),
            primary: hexToHsl("#A78BFA"),
            "primary-foreground": hexToHsl("#2E1065"),
            secondary: hexToHsl("#5B21B6"),
            "secondary-foreground": hexToHsl("#EDE9FE"),
            muted: hexToHsl("#5B21B6"),
            "muted-foreground": hexToHsl("#C4B5FD"),
            accent: hexToHsl("#8B5CF6"),
            "accent-foreground": hexToHsl("#EDE9FE"),
            destructive: hexToHsl("#F87171"),
            "destructive-foreground": hexToHsl("#2E1065"),
            border: hexToHsl("#5B21B6"),
            input: hexToHsl("#5B21B6"),
            ring: hexToHsl("#8B5CF6"),
        },
    },
  },
  {
      name: 'COLOR_SCHEME_22',
      label: 'Goldenrod',
      colors: {
          light: {
              background: hexToHsl("#FFFBEB"),
              foreground: hexToHsl("#713F12"),
              card: hexToHsl("#FFFFFF"),
              "card-foreground": hexToHsl("#713F12"),
              popover: hexToHsl("#FFFFFF"),
              "popover-foreground": hexToHsl("#713F12"),
              primary: hexToHsl("#F59E0B"),
              "primary-foreground": hexToHsl("#FFFFFF"),
              secondary: hexToHsl("#FEF3C7"),
              "secondary-foreground": hexToHsl("#713F12"),
              muted: hexToHsl("#FEF3C7"),
              "muted-foreground": hexToHsl("#92400E"),
              accent: hexToHsl("#FBBF24"),
              "accent-foreground": hexToHsl("#713F12"),
              destructive: hexToHsl("#EF4444"),
              "destructive-foreground": hexToHsl("#FFFFFF"),
              border: hexToHsl("#FDE68A"),
              input: hexToHsl("#FDE68A"),
              ring: hexToHsl("#FBBF24"),
          },
          dark: {
              background: hexToHsl("#422006"),
              foreground: hexToHsl("#FEF3C7"),
              card: hexToHsl("#573A1A"),
              "card-foreground": hexToHsl("#FEF3C7"),
              popover: hexToHsl("#573A1A"),
              "popover-foreground": hexToHsl("#FEF3C7"),
              primary: hexToHsl("#FBBF24"),
              "primary-foreground": hexToHsl("#422006"),
              secondary: hexToHsl("#713F12"),
              "secondary-foreground": hexToHsl("#FEF3C7"),
              muted: hexToHsl("#713F12"),
              "muted-foreground": hexToHsl("#FDE68A"),
              accent: hexToHsl("#F59E0B"),
              "accent-foreground": hexToHsl("#FEF3C7"),
              destructive: hexToHsl("#F87171"),
              "destructive-foreground": hexToHsl("#422006"),
              border: hexToHsl("#713F12"),
              input: hexToHsl("#713F12"),
              ring: hexToHsl("#F59E0B"),
          },
      },
  },
  {
      name: 'COLOR_SCHEME_23',
      label: 'Deep Sea',
      colors: {
          light: {
              background: hexToHsl("#F0F9FF"),
              foreground: hexToHsl("#0C4A6E"),
              card: hexToHsl("#FFFFFF"),
              "card-foreground": hexToHsl("#0C4A6E"),
              popover: hexToHsl("#FFFFFF"),
              "popover-foreground": hexToHsl("#0C4A6E"),
              primary: hexToHsl("#0369A1"),
              "primary-foreground": hexToHsl("#FFFFFF"),
              secondary: hexToHsl("#E0F2FE"),
              "secondary-foreground": hexToHsl("#0C4A6E"),
              muted: hexToHsl("#E0F2FE"),
              "muted-foreground": hexToHsl("#075985"),
              accent: hexToHsl("#0EA5E9"),
              "accent-foreground": hexToHsl("#FFFFFF"),
              destructive: hexToHsl("#EF4444"),
              "destructive-foreground": hexToHsl("#FFFFFF"),
              border: hexToHsl("#BAE6FD"),
              input: hexToHsl("#BAE6FD"),
              ring: hexToHsl("#0EA5E9"),
          },
          dark: {
              background: hexToHsl("#082F49"),
              foreground: hexToHsl("#E0F2FE"),
              card: hexToHsl("#0C4A6E"),
              "card-foreground": hexToHsl("#E0F2FE"),
              popover: hexToHsl("#0C4A6E"),
              "popover-foreground": hexToHsl("#E0F2FE"),
              primary: hexToHsl("#38BDF8"),
              "primary-foreground": hexToHsl("#082F49"),
              secondary: hexToHsl("#0369A1"),
              "secondary-foreground": hexToHsl("#E0F2FE"),
              muted: hexToHsl("#0369A1"),
              "muted-foreground": hexToHsl("#7DD3FC"),
              accent: hexToHsl("#0EA5E9"),
              "accent-foreground": hexToHsl("#082F49"),
              destructive: hexToHsl("#F87171"),
              "destructive-foreground": hexToHsl("#082F49"),
              border: hexToHsl("#0369A1"),
              input: hexToHsl("#0369A1"),
              ring: hexToHsl("#0EA5E9"),
          },
      },
  },
  {
      name: 'COLOR_SCHEME_24',
      label: 'Ruby Red',
      colors: {
          light: {
              background: hexToHsl("#FEF2F2"),
              foreground: hexToHsl("#7F1D1D"),
              card: hexToHsl("#FFFFFF"),
              "card-foreground": hexToHsl("#7F1D1D"),
              popover: hexToHsl("#FFFFFF"),
              "popover-foreground": hexToHsl("#7F1D1D"),
              primary: hexToHsl("#B91C1C"),
              "primary-foreground": hexToHsl("#FFFFFF"),
              secondary: hexToHsl("#FEE2E2"),
              "secondary-foreground": hexToHsl("#7F1D1D"),
              muted: hexToHsl("#FEE2E2"),
              "muted-foreground": hexToHsl("#991B1B"),
              accent: hexToHsl("#DC2626"),
              "accent-foreground": hexToHsl("#FFFFFF"),
              destructive: hexToHsl("#EF4444"),
              "destructive-foreground": hexToHsl("#FFFFFF"),
              border: hexToHsl("#FECACA"),
              input: hexToHsl("#FECACA"),
              ring: hexToHsl("#DC2626"),
          },
          dark: {
              background: hexToHsl("#450A0A"),
              foreground: hexToHsl("#FEE2E2"),
              card: hexToHsl("#7F1D1D"),
              "card-foreground": hexToHsl("#FEE2E2"),
              popover: hexToHsl("#7F1D1D"),
              "popover-foreground": hexToHsl("#FEE2E2"),
              primary: hexToHsl("#F87171"),
              "primary-foreground": hexToHsl("#450A0A"),
              secondary: hexToHsl("#991B1B"),
              "secondary-foreground": hexToHsl("#FEE2E2"),
              muted: hexToHsl("#991B1B"),
              "muted-foreground": hexToHsl("#FCA5A5"),
              accent: hexToHsl("#DC2626"),
              "accent-foreground": hexToHsl("#FEE2E2"),
              destructive: hexToHsl("#F87171"),
              "destructive-foreground": hexToHsl("#450A0A"),
              border: hexToHsl("#991B1B"),
              input: hexToHsl("#991B1B"),
              ring: hexToHsl("#DC2626"),
          },
      },
  },
  {
      name: 'COLOR_SCHEME_25',
      label: 'Tangerine',
      colors: {
          light: {
              background: hexToHsl("#FFF7ED"),
              foreground: hexToHsl("#7C2D12"),
              card: hexToHsl("#FFFFFF"),
              "card-foreground": hexToHsl("#7C2D12"),
              popover: hexToHsl("#FFFFFF"),
              "popover-foreground": hexToHsl("#7C2D12"),
              primary: hexToHsl("#EA580C"),
              "primary-foreground": hexToHsl("#FFFFFF"),
              secondary: hexToHsl("#FFEDD5"),
              "secondary-foreground": hexToHsl("#7C2D12"),
              muted: hexToHsl("#FFEDD5"),
              "muted-foreground": hexToHsl("#9A3412"),
              accent: hexToHsl("#F97316"),
              "accent-foreground": hexToHsl("#FFFFFF"),
              destructive: hexToHsl("#EF4444"),
              "destructive-foreground": hexToHsl("#FFFFFF"),
              border: hexToHsl("#FED7AA"),
              input: hexToHsl("#FED7AA"),
              ring: hexToHsl("#F97316"),
          },
          dark: {
              background: hexToHsl("#431407"),
              foreground: hexToHsl("#FFEDD5"),
              card: hexToHsl("#7C2D12"),
              "card-foreground": hexToHsl("#FFEDD5"),
              popover: hexToHsl("#7C2D12"),
              "popover-foreground": hexToHsl("#FFEDD5"),
              primary: hexToHsl("#FB923C"),
              "primary-foreground": hexToHsl("#431407"),
              secondary: hexToHsl("#9A3412"),
              "secondary-foreground": hexToHsl("#FFEDD5"),
              muted: hexToHsl("#9A3412"),
              "muted-foreground": hexToHsl("#FDBA74"),
              accent: hexToHsl("#F97316"),
              "accent-foreground": hexToHsl("#431407"),
              destructive: hexToHsl("#F87171"),
              "destructive-foreground": hexToHsl("#431407"),
              border: hexToHsl("#9A3412"),
              input: hexToHsl("#9A3412"),
              ring: hexToHsl("#F97316"),
          },
      },
  },
  {
      name: 'COLOR_SCHEME_26',
      label: 'Sapphire',
      colors: {
          light: {
              background: hexToHsl("#F0F9FF"),
              foreground: hexToHsl("#1E3A8A"),
              card: hexToHsl("#FFFFFF"),
              "card-foreground": hexToHsl("#1E3A8A"),
              popover: hexToHsl("#FFFFFF"),
              "popover-foreground": hexToHsl("#1E3A8A"),
              primary: hexToHsl("#2563EB"),
              "primary-foreground": hexToHsl("#FFFFFF"),
              secondary: hexToHsl("#DBEAFE"),
              "secondary-foreground": hexToHsl("#1E3A8A"),
              muted: hexToHsl("#DBEAFE"),
              "muted-foreground": hexToHsl("#1D4ED8"),
              accent: hexToHsl("#3B82F6"),
              "accent-foreground": hexToHsl("#FFFFFF"),
              destructive: hexToHsl("#EF4444"),
              "destructive-foreground": hexToHsl("#FFFFFF"),
              border: hexToHsl("#BFDBFE"),
              input: hexToHsl("#BFDBFE"),
              ring: hexToHsl("#3B82F6"),
          },
          dark: {
              background: hexToHsl("#1E293B"),
              foreground: hexToHsl("#DBEAFE"),
              card: hexToHsl("#1E3A8A"),
              "card-foreground": hexToHsl("#DBEAFE"),
              popover: hexToHsl("#1E3A8A"),
              "popover-foreground": hexToHsl("#DBEAFE"),
              primary: hexToHsl("#60A5FA"),
              "primary-foreground": hexToHsl("#1E293B"),
              secondary: hexToHsl("#2563EB"),
              "secondary-foreground": hexToHsl("#DBEAFE"),
              muted: hexToHsl("#2563EB"),
              "muted-foreground": hexToHsl("#93C5FD"),
              accent: hexToHsl("#3B82F6"),
              "accent-foreground": hexToHsl("#1E293B"),
              destructive: hexToHsl("#F87171"),
              "destructive-foreground": hexToHsl("#1E293B"),
              border: hexToHsl("#2563EB"),
              input: hexToHsl("#2563EB"),
              ring: hexToHsl("#3B82F6"),
          },
      },
  },
  {
      name: 'COLOR_SCHEME_27',
      label: 'Jade',
      colors: {
          light: {
              background: hexToHsl("#F0FDF4"),
              foreground: hexToHsl("#064E3B"),
              card: hexToHsl("#FFFFFF"),
              "card-foreground": hexToHsl("#064E3B"),
              popover: hexToHsl("#FFFFFF"),
              "popover-foreground": hexToHsl("#064E3B"),
              primary: hexToHsl("#059669"),
              "primary-foreground": hexToHsl("#FFFFFF"),
              secondary: hexToHsl("#D1FAE5"),
              "secondary-foreground": hexToHsl("#064E3B"),
              muted: hexToHsl("#D1FAE5"),
              "muted-foreground": hexToHsl("#047857"),
              accent: hexToHsl("#10B981"),
              "accent-foreground": hexToHsl("#FFFFFF"),
              destructive: hexToHsl("#EF4444"),
              "destructive-foreground": hexToHsl("#FFFFFF"),
              border: hexToHsl("#A7F3D0"),
              input: hexToHsl("#A7F3D0"),
              ring: hexToHsl("#10B981"),
          },
          dark: {
              background: hexToHsl("#022C22"),
              foreground: hexToHsl("#D1FAE5"),
              card: hexToHsl("#064E3B"),
              "card-foreground": hexToHsl("#D1FAE5"),
              popover: hexToHsl("#064E3B"),
              "popover-foreground": hexToHsl("#D1FAE5"),
              primary: hexToHsl("#34D399"),
              "primary-foreground": hexToHsl("#022C22"),
              secondary: hexToHsl("#059669"),
              "secondary-foreground": hexToHsl("#D1FAE5"),
              muted: hexToHsl("#059669"),
              "muted-foreground": hexToHsl("#6EE7B7"),
              accent: hexToHsl("#10B981"),
              "accent-foreground": hexToHsl("#022C22"),
              destructive: hexToHsl("#F87171"),
              "destructive-foreground": hexToHsl("#022C22"),
              border: hexToHsl("#059669"),
              input: hexToHsl("#059669"),
              ring: hexToHsl("#10B981"),
          },
      },
  },
  {
      name: 'COLOR_SCHEME_28',
      label: 'Rose Quartz',
      colors: {
          light: {
              background: hexToHsl("#FFF1F2"),
              foreground: hexToHsl("#881337"),
              card: hexToHsl("#FFFFFF"),
              "card-foreground": hexToHsl("#881337"),
              popover: hexToHsl("#FFFFFF"),
              "popover-foreground": hexToHsl("#881337"),
              primary: hexToHsl("#DB2777"),
              "primary-foreground": hexToHsl("#FFFFFF"),
              secondary: hexToHsl("#FCE7F3"),
              "secondary-foreground": hexToHsl("#881337"),
              muted: hexToHsl("#FCE7F3"),
              "muted-foreground": hexToHsl("#9D174D"),
              accent: hexToHsl("#EC4899"),
              "accent-foreground": hexToHsl("#FFFFFF"),
              destructive: hexToHsl("#EF4444"),
              "destructive-foreground": hexToHsl("#FFFFFF"),
              border: hexToHsl("#FBCFE8"),
              input: hexToHsl("#FBCFE8"),
              ring: hexToHsl("#EC4899"),
          },
          dark: {
              background: hexToHsl("#5F0A21"),
              foreground: hexToHsl("#FCE7F3"),
              card: hexToHsl("#881337"),
              "card-foreground": hexToHsl("#FCE7F3"),
              popover: hexToHsl("#881337"),
              "popover-foreground": hexToHsl("#FCE7F3"),
              primary: hexToHsl("#F472B6"),
              "primary-foreground": hexToHsl("#5F0A21"),
              secondary: hexToHsl("#9D174D"),
              "secondary-foreground": hexToHsl("#FCE7F3"),
              muted: hexToHsl("#9D174D"),
              "muted-foreground": hexToHsl("#F9A8D4"),
              accent: hexToHsl("#EC4899"),
              "accent-foreground": hexToHsl("#5F0A21"),
              destructive: hexToHsl("#F87171"),
              "destructive-foreground": hexToHsl("#5F0A21"),
              border: hexToHsl("#9D174D"),
              input: hexToHsl("#9D174D"),
              ring: hexToHsl("#EC4899"),
          },
      },
  },
  {
      name: 'COLOR_SCHEME_29',
      label: 'Arctic Blue',
      colors: {
          light: {
              background: hexToHsl("#F0F9FF"),
              foreground: hexToHsl("#083344"),
              card: hexToHsl("#FFFFFF"),
              "card-foreground": hexToHsl("#083344"),
              popover: hexToHsl("#FFFFFF"),
              "popover-foreground": hexToHsl("#083344"),
              primary: hexToHsl("#06B6D4"),
              "primary-foreground": hexToHsl("#FFFFFF"),
              secondary: hexToHsl("#CFFAFE"),
              "secondary-foreground": hexToHsl("#083344"),
              muted: hexToHsl("#CFFAFE"),
              "muted-foreground": hexToHsl("#0E7490"),
              accent: hexToHsl("#22D3EE"),
              "accent-foreground": hexToHsl("#083344"),
              destructive: hexToHsl("#EF4444"),
              "destructive-foreground": hexToHsl("#FFFFFF"),
              border: hexToHsl("#A5F3FC"),
              input: hexToHsl("#A5F3FC"),
              ring: hexToHsl("#22D3EE"),
          },
          dark: {
              background: hexToHsl("#0E2A37"),
              foreground: hexToHsl("#CFFAFE"),
              card: hexToHsl("#083344"),
              "card-foreground": hexToHsl("#CFFAFE"),
              popover: hexToHsl("#083344"),
              "popover-foreground": hexToHsl("#CFFAFE"),
              primary: hexToHsl("#22D3EE"),
              "primary-foreground": hexToHsl("#0E2A37"),
              secondary: hexToHsl("#0E7490"),
              "secondary-foreground": hexToHsl("#CFFAFE"),
              muted: hexToHsl("#0E7490"),
              "muted-foreground": hexToHsl("#67E8F9"),
              accent: hexToHsl("#06B6D4"),
              "accent-foreground": hexToHsl("#0E2A37"),
              destructive: hexToHsl("#F87171"),
              "destructive-foreground": hexToHsl("#0E2A37"),
              border: hexToHsl("#0E7490"),
              input: hexToHsl("#0E7490"),
              ring: hexToHsl("#06B6D4"),
          },
      },
  },
  {
      name: 'COLOR_SCHEME_30',
      label: 'Fuchsia',
      colors: {
          light: {
              background: hexToHsl("#FAF5FF"),
              foreground: hexToHsl("#5B21B6"),
              card: hexToHsl("#FFFFFF"),
              "card-foreground": hexToHsl("#5B21B6"),
              popover: hexToHsl("#FFFFFF"),
              "popover-foreground": hexToHsl("#5B21B6"),
              primary: hexToHsl("#C026D3"),
              "primary-foreground": hexToHsl("#FFFFFF"),
              secondary: hexToHsl("#F3E8FF"),
              "secondary-foreground": hexToHsl("#5B21B6"),
              muted: hexToHsl("#F3E8FF"),
              "muted-foreground": hexToHsl("#7E22CE"),
              accent: hexToHsl("#D946EF"),
              "accent-foreground": hexToHsl("#FFFFFF"),
              destructive: hexToHsl("#EF4444"),
              "destructive-foreground": hexToHsl("#FFFFFF"),
              border: hexToHsl("#E9D5FF"),
              input: hexToHsl("#E9D5FF"),
              ring: hexToHsl("#D946EF"),
          },
          dark: {
              background: hexToHsl("#2E1065"),
              foreground: hexToHsl("#F3E8FF"),
              card: hexToHsl("#5B21B6"),
              "card-foreground": hexToHsl("#F3E8FF"),
              popover: hexToHsl("#5B21B6"),
              "popover-foreground": hexToHsl("#F3E8FF"),
              primary: hexToHsl("#E879F9"),
              "primary-foreground": hexToHsl("#2E1065"),
              secondary: hexToHsl("#7E22CE"),
              "secondary-foreground": hexToHsl("#F3E8FF"),
              muted: hexToHsl("#7E22CE"),
              "muted-foreground": hexToHsl("#D8B4FE"),
              accent: hexToHsl("#D946EF"),
              "accent-foreground": hexToHsl("#2E1065"),
              destructive: hexToHsl("#F87171"),
              "destructive-foreground": hexToHsl("#2E1065"),
              border: hexToHsl("#7E22CE"),
              input: hexToHsl("#7E22CE"),
              ring: hexToHsl("#D946EF"),
          },
      },
  }
];
